export type PermissionSeed = {
  nombre: string;
  descripcion: string;
};

export const TENANT_PERMISSIONS: PermissionSeed[] = [
  { nombre: "ver_empleados", descripcion: "Permiso para ver los empleados" },
  { nombre: "crear_empleados", descripcion: "Permiso para crear los empleados" },
  { nombre: "editar_empleado", descripcion: "Permiso para editar los empleados" },
  { nombre: "ver_permisos", descripcion: "Permiso para ver los permisos" },
  { nombre: "ver_roles", descripcion: "Permiso para ver roles" },
  { nombre: "crear_roles", descripcion: "Permiso para crear roles" },
  { nombre: "editar_roles", descripcion: "Permiso para editar roles" },
  { nombre: "ver_usuarios", descripcion: "Permiso para ver usuarios" },
  { nombre: "crear_usuario", descripcion: "Permiso para crear usuarios" },
  { nombre: "editar_usuario", descripcion: "Permiso para editar usuarios" },
  { nombre: "ver_puestos", descripcion: "Permiso para ver puestos" },
  { nombre: "crear_puestos", descripcion: "Permiso para crear puestos" },
  { nombre: "editar_puestos", descripcion: "Permiso para editar puestos" },
  { nombre: "ver_profile", descripcion: "Permiso para ver el perfil" },
  { nombre: "editar_tenant", descripcion: "Permiso para editar el contacto del tenant" },
  { nombre: "ver_seguros", descripcion: "Permiso para ver seguros" },
  { nombre: "crear_seguros", descripcion: "Permiso para crear seguros" },
  { nombre: "editar_seguros", descripcion: "Permiso para editar seguros" },
  { nombre: "ver_pacientes", descripcion: "Permiso para ver pacientes" },
  { nombre: "crear_pacientes", descripcion: "Permiso para crear pacientes" },
  { nombre: "editar_pacientes", descripcion: "Permiso para editar pacientes" },
  { nombre: "ver_profesiones", descripcion: "Permiso para ver profesiones" },
  { nombre: "crear_profesiones", descripcion: "Permiso para crear profesiones" },
  { nombre: "editar_profesiones", descripcion: "Permiso para editar profesiones" },
  { nombre: "ver_medicos", descripcion: "Permiso para ver medicos" },
  { nombre: "crear_medicos", descripcion: "Permiso para crear medicos" },
  { nombre: "editar_medicos", descripcion: "Permiso para editar medicos" },
  { nombre: "ver_servicios", descripcion: "Permiso para ver servicios" },
  { nombre: "crear_servicios", descripcion: "Permiso para crear servicios" },
  { nombre: "editar_servicios", descripcion: "Permiso para editar servicios" },
  { nombre: "ver_consultorios", descripcion: "Permiso para ver consultorios" },
  { nombre: "crear_consultorios", descripcion: "Permiso para crear consultorios" },
  { nombre: "editar_consultorios", descripcion: "Permiso para editar consultorios" },
  { nombre: "ver_citas", descripcion: "Permiso para ver citas" },
  { nombre: "crear_citas", descripcion: "Permiso para crear citas" },
  { nombre: "editar_citas", descripcion: "Permiso para editar citas" },
  { nombre: "ver_cotizaciones", descripcion: "Permiso para ver cotizaciones" },
  { nombre: "crear_cotizaciones", descripcion: "Permiso para crear cotizaciones" },
  { nombre: "editar_cotizaciones", descripcion: "Permiso para editar cotizaciones" },
  { nombre: "ver_planes_tratamiento", descripcion: "Permiso para ver planes de tratamiento" },
  { nombre: "crear_planes_tratamiento", descripcion: "Permiso para crear planes de tratamiento" },
  { nombre: "editar_planes_tratamiento", descripcion: "Permiso para editar planes de tratamiento" },
  { nombre: "ver_pagos", descripcion: "Permiso para ver pagos y financiamientos" },
  { nombre: "crear_pagos", descripcion: "Permiso para registrar pagos" },
  { nombre: "crear_financiamiento", descripcion: "Permiso para crear financiamientos" },
  { nombre: "ver_inventario", descripcion: "Permiso para ver inventario de productos" },
  { nombre: "crear_inventario", descripcion: "Permiso para crear inventario" },
  { nombre: "editar_inventario", descripcion: "Permiso para editar inventario" },
];

export const PLATFORM_PERMISSIONS: PermissionSeed[] = [
  { nombre: "ver_dashboard_admin", descripcion: "Permiso para ver dashboard global de tenants" },
  { nombre: "gestionar_tenants", descripcion: "Permiso para crear y gestionar tenants" },
  { nombre: "ver_tenants", descripcion: "Permiso para visualizar el módulo de tenants" },
  { nombre: "ver_paquetes", descripcion: "Permiso para visualizar el módulo de paquetes" },
  { nombre: "gestionar_paquetes", descripcion: "Permiso para crear y editar paquetes" },
];
