CREATE TABLE `ExpedienteClinicoPaciente` (
  `id` VARCHAR(36) NOT NULL,
  `tenantId` VARCHAR(36) NULL,
  `pacienteId` VARCHAR(36) NOT NULL,
  `tiempoEnfermedad` TEXT NULL,
  `signosSintomasPrincipales` TEXT NULL,
  `relatoCronologico` TEXT NULL,
  `funcionesBiologicas` TEXT NULL,
  `antecedentesFamiliares` TEXT NULL,
  `antecedentesPersonales` TEXT NULL,
  `presionAlta` BIT(1) NULL,
  `presionBaja` BIT(1) NULL,
  `hepatitis` BIT(1) NULL,
  `gastritis` BIT(1) NULL,
  `vih` BIT(1) NULL,
  `diabetes` BIT(1) NULL,
  `asma` BIT(1) NULL,
  `fuma` BIT(1) NULL,
  `comentarioAdicional` TEXT NULL,
  `enfermedadesSanguineas` BIT(1) NULL,
  `enfermedadesSanguineasCuales` TEXT NULL,
  `problemasCardiacos` BIT(1) NULL,
  `problemasCardiacosCuales` TEXT NULL,
  `otraEnfermedad` TEXT NULL,
  `cepilladoDentalFrecuencia` VARCHAR(100) NULL,
  `sangranEncias` BIT(1) NULL,
  `hemorragiasExtraccion` BIT(1) NULL,
  `bruxismo` BIT(1) NULL,
  `otraMolestiaBoca` TEXT NULL,
  `alergias` TEXT NULL,
  `operacionGrandeReciente` TEXT NULL,
  `medicacionPermanente` TEXT NULL,
  `presionArterial` VARCHAR(50) NULL,
  `frecuenciaCardiaca` VARCHAR(50) NULL,
  `temperatura` VARCHAR(50) NULL,
  `frecuenciaRespiratoria` VARCHAR(50) NULL,
  `examenExtraoral` TEXT NULL,
  `examenIntraoral` TEXT NULL,
  `createAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updateAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `ExpedienteClinicoPaciente_pacienteId_key`(`pacienteId`),
  INDEX `ExpedienteClinicoPaciente_tenantId_idx`(`tenantId`),
  INDEX `ExpedienteClinicoPaciente_pacienteId_idx`(`pacienteId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `ExpedienteClinicoPaciente` ADD CONSTRAINT `ExpedienteClinicoPaciente_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ExpedienteClinicoPaciente` ADD CONSTRAINT `ExpedienteClinicoPaciente_pacienteId_fkey` FOREIGN KEY (`pacienteId`) REFERENCES `Paciente`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
